pre-release-commit-message = "chore: Release"
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
sign-tag = true
sign-commit = true
consolidate-commits = true
allow-branch = ["main"]
pre-release-replacements = [
    { file = "README.md", search = "kdeets 0.*", replace = "{{crate_name}} {{version}}" },
    { file = "tests/cmd/version.trycmd", search = "kdeets 0.*", replace = "{{crate_name}} {{version}}" },
    { file = "tests/cmd/version.trycmd", search = "kdeets-crate 0.*", replace = "{{crate_name}}-crate {{version}}" },
    { file = "CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [{{version}}] - {{date}}", exactly = 1 },
    { file = "CHANGELOG.md", search = "\\[Unreleased\\]:", replace = "[{{version}}]:", exactly = 1 },
    { file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", exactly = 1 },
]
